const heroOptions = [
  { id: 1, value: `A-Bomb` },
  { id: 2, value: `Abe Sapien` },
  { id: 3, value: `Abin Sur` },
  { id: 4, value: `Abomination` },
  { id: 5, value: `Abraxas` },
  { id: 6, value: `Absorbing Man` },
  { id: 7, value: `Adam Monroe` },
  { id: 8, value: `Adam Strange` },
  { id: 9, value: `Agent 13` },
  { id: 10, value: `Agent Bob` },
  { id: 11, value: `Agent Zero` },
  { id: 12, value: `Air-Walker` },
  { id: 13, value: `Ajax` },
  { id: 14, value: `Alan Scott` },
  { id: 15, value: `Alex Mercer` },
  { id: 16, value: `Alex Woolsly` },
  { id: 17, value: `Alfred Pennyworth` },
  { id: 18, value: `Alien` },
  { id: 19, value: `Allan Quatermain` },
  { id: 20, value: `Amazo` },
  { id: 21, value: `Ammo` },
  { id: 22, value: `Ando Masahashi` },
  { id: 23, value: `Angel` },
  { id: 24, value: `Angel` },
  { id: 25, value: `Angel Dust` },
  { id: 26, value: `Angel Salvadore` },
  { id: 27, value: `Angela` },
  { id: 28, value: `Animal Man` },
  { id: 29, value: `Annihilus` },
  { id: 30, value: `Ant-Man` },
  { id: 31, value: `Ant-Man II` },
  { id: 32, value: `Anti-Monitor` },
  { id: 33, value: `Anti-Spawn` },
  { id: 34, value: `Anti-Venom` },
  { id: 35, value: `Apocalypse` },
  { id: 36, value: `Aquababy` },
  { id: 37, value: `Aqualad` },
  { id: 38, value: `Aquaman` },
  { id: 39, value: `Arachne` },
  { id: 40, value: `Archangel` },
  { id: 41, value: `Arclight` },
  { id: 42, value: `Ardina` },
  { id: 43, value: `Ares` },
  { id: 44, value: `Ariel` },
  { id: 45, value: `Armor` },
  { id: 46, value: `Arsenal` },
  { id: 47, value: `Astro Boy` },
  { id: 48, value: `Atlas` },
  { id: 49, value: `Atlas` },
  { id: 50, value: `Atom` },
  { id: 51, value: `Atom` },
  { id: 52, value: `Atom Girl` },
  { id: 53, value: `Atom II` },
  { id: 54, value: `Atom III` },
  { id: 55, value: `Atom IV` },
  { id: 56, value: `Aurora` },
  { id: 57, value: `Azazel` },
  { id: 58, value: `Azrael` },
  { id: 59, value: `Aztar` },
  { id: 60, value: `Bane` },
  { id: 61, value: `Banshee` },
  { id: 62, value: `Bantam` },
  { id: 63, value: `Batgirl` },
  { id: 64, value: `Batgirl` },
  { id: 65, value: `Batgirl III` },
  { id: 66, value: `Batgirl IV` },
  { id: 67, value: `Batgirl V` },
  { id: 68, value: `Batgirl VI` },
  { id: 69, value: `Batman` },
  { id: 70, value: `Batman` },
  { id: 71, value: `Batman II` },
  { id: 72, value: `Battlestar` },
  { id: 73, value: `Batwoman V` },
  { id: 74, value: `Beak` },
  { id: 75, value: `Beast` },
  { id: 76, value: `Beast Boy` },
  { id: 77, value: `Beetle` },
  { id: 78, value: `Ben 10` },
  { id: 79, value: `Beta Ray Bill` },
  { id: 80, value: `Beyonder` },
  { id: 81, value: `Big Barda` },
  { id: 82, value: `Big Daddy` },
  { id: 83, value: `Big Man` },
  { id: 84, value: `Bill Harken` },
  { id: 85, value: `Billy Kincaid` },
  { id: 86, value: `Binary` },
  { id: 87, value: `Bionic Woman` },
  { id: 88, value: `Bird-Brain` },
  { id: 89, value: `Bird-Man` },
  { id: 90, value: `Bird-Man II` },
  { id: 91, value: `Birdman` },
  { id: 92, value: `Bishop` },
  { id: 93, value: `Bizarro` },
  { id: 94, value: `Black Abbott` },
  { id: 95, value: `Black Adam` },
  { id: 96, value: `Black Bolt` },
  { id: 97, value: `Black Canary` },
  { id: 98, value: `Black Canary` },
  { id: 99, value: `Black Cat` },
  { id: 100, value: `Black Flash` },
  { id: 101, value: `Black Goliath` },
  { id: 102, value: `Black Knight III` },
  { id: 103, value: `Black Lightning` },
  { id: 104, value: `Black Mamba` },
  { id: 105, value: `Black Manta` },
  { id: 106, value: `Black Panther` },
  { id: 107, value: `Black Widow` },
  { id: 108, value: `Black Widow II` },
  { id: 109, value: `Blackout` },
  { id: 110, value: `Blackwing` },
  { id: 111, value: `Blackwulf` },
  { id: 112, value: `Blade` },
  { id: 113, value: `Blaquesmith` },
  { id: 114, value: `Bling!` },
  { id: 115, value: `Blink` },
  { id: 116, value: `Blizzard` },
  { id: 117, value: `Blizzard` },
  { id: 118, value: `Blizzard II` },
  { id: 119, value: `Blob` },
  { id: 120, value: `Bloodaxe` },
  { id: 121, value: `Bloodhawk` },
  { id: 122, value: `Bloodwraith` },
  { id: 123, value: `Blue Beetle` },
  { id: 124, value: `Blue Beetle` },
  { id: 125, value: `Blue Beetle II` },
  { id: 126, value: `Blue Beetle III` },
  { id: 127, value: `Boba Fett` },
  { id: 128, value: `Bolt` },
  { id: 129, value: `Bomb Queen` },
  { id: 130, value: `Boom-Boom` },
  { id: 131, value: `Boomer` },
  { id: 132, value: `Booster Gold` },
  { id: 133, value: `Box` },
  { id: 134, value: `Box III` },
  { id: 135, value: `Box IV` },
  { id: 136, value: `Brainiac` },
  { id: 137, value: `Brainiac 5` },
  { id: 138, value: `Brother Voodoo` },
  { id: 139, value: `Brundlefly` },
  { id: 140, value: `Buffy` },
  { id: 141, value: `Bullseye` },
  { id: 142, value: `Bumblebee` },
  { id: 143, value: `Bumbleboy` },
  { id: 144, value: `Bushido` },
  { id: 145, value: `Cable` },
  { id: 146, value: `Callisto` },
  { id: 147, value: `Cameron Hicks` },
  { id: 148, value: `Cannonball` },
  { id: 149, value: `Captain America` },
  { id: 150, value: `Captain Atom` },
  { id: 151, value: `Captain Britain` },
  { id: 152, value: `Captain Cold` },
  { id: 153, value: `Captain Epic` },
  { id: 154, value: `Captain Hindsight` },
  { id: 155, value: `Captain Mar-vell` },
  { id: 156, value: `Captain Marvel` },
  { id: 157, value: `Captain Marvel` },
  { id: 158, value: `Captain Marvel II` },
  { id: 159, value: `Captain Midnight` },
  { id: 160, value: `Captain Planet` },
  { id: 161, value: `Captain Universe` },
  { id: 162, value: `Carnage` },
  { id: 163, value: `Cat` },
  { id: 164, value: `Cat II` },
  { id: 165, value: `Catwoman` },
  { id: 166, value: `Cecilia Reyes` },
  { id: 167, value: `Century` },
  { id: 168, value: `Cerebra` },
  { id: 169, value: `Chamber` },
  { id: 170, value: `Chameleon` },
  { id: 171, value: `Changeling` },
  { id: 172, value: `Cheetah` },
  { id: 173, value: `Cheetah II` },
  { id: 174, value: `Cheetah III` },
  { id: 175, value: `Chromos` },
  { id: 176, value: `Chuck Norris` },
  { id: 177, value: `Citizen Steel` },
  { id: 178, value: `Claire Bennet` },
  { id: 179, value: `Clea` },
  { id: 180, value: `Cloak` },
  { id: 181, value: `Clock King` },
  { id: 182, value: `Cogliostro` },
  { id: 183, value: `Colin Wagner` },
  { id: 184, value: `Colossal Boy` },
  { id: 185, value: `Colossus` },
  { id: 186, value: `Copycat` },
  { id: 187, value: `Corsair` },
  { id: 188, value: `Cottonmouth` },
  { id: 189, value: `Crimson Crusader` },
  { id: 190, value: `Crimson Dynamo` },
  { id: 191, value: `Crystal` },
  { id: 192, value: `Curse` },
  { id: 193, value: `Cy-Gor` },
  { id: 194, value: `Cyborg` },
  { id: 195, value: `Cyborg Superman` },
  { id: 196, value: `Cyclops` },
  { id: 197, value: `Cypher` },
  { id: 198, value: `Dagger` },
  { id: 199, value: `Danny Cooper` },
  { id: 200, value: `Daphne Powell` },
  { id: 201, value: `Daredevil` },
  { id: 202, value: `Darkhawk` },
  { id: 203, value: `Darkman` },
  { id: 204, value: `Darkseid` },
  { id: 205, value: `Darkside` },
  { id: 206, value: `Darkstar` },
  { id: 207, value: `Darth Maul` },
  { id: 208, value: `Darth Vader` },
  { id: 209, value: `Dash` },
  { id: 210, value: `Data` },
  { id: 211, value: `Dazzler` },
  { id: 212, value: `Deadman` },
  { id: 213, value: `Deadpool` },
  { id: 214, value: `Deadshot` },
  { id: 215, value: `Deathlok` },
  { id: 216, value: `Deathstroke` },
  { id: 217, value: `Demogoblin` },
  { id: 218, value: `Destroyer` },
  { id: 219, value: `Diamondback` },
  { id: 220, value: `DL Hawkins` },
  { id: 221, value: `Doc Samson` },
  { id: 222, value: `Doctor Doom` },
  { id: 223, value: `Doctor Doom II` },
  { id: 224, value: `Doctor Fate` },
  { id: 225, value: `Doctor Octopus` },
  { id: 226, value: `Doctor Strange` },
  { id: 227, value: `Domino` },
  { id: 228, value: `Donatello` },
  { id: 229, value: `Donna Troy` },
  { id: 230, value: `Doomsday` },
  { id: 231, value: `Doppelganger` },
  { id: 232, value: `Dormammu` },
  { id: 233, value: `Dr Manhattan` },
  { id: 234, value: `Drax the Destroyer` },
  { id: 235, value: `Ego` },
  { id: 236, value: `Elastigirl` },
  { id: 237, value: `Electro` },
  { id: 238, value: `Elektra` },
  { id: 239, value: `Elle Bishop` },
  { id: 240, value: `Elongated Man` },
  { id: 241, value: `Emma Frost` },
  { id: 242, value: `Enchantress` },
  { id: 243, value: `Energy` },
  { id: 244, value: `ERG-1` },
  { id: 245, value: `Ethan Hunt` },
  { id: 246, value: `Etrigan` },
  { id: 247, value: `Evil Deadpool` },
  { id: 248, value: `Evilhawk` },
  { id: 249, value: `Exodus` },
  { id: 250, value: `Fabian Cortez` },
  { id: 251, value: `Falcon` },
  { id: 252, value: `Fallen One II` },
  { id: 253, value: `Faora` },
  { id: 254, value: `Feral` },
  { id: 255, value: `Fighting Spirit` },
  { id: 256, value: `Fin Fang Foom` },
  { id: 257, value: `Firebird` },
  { id: 258, value: `Firelord` },
  { id: 259, value: `Firestar` },
  { id: 260, value: `Firestorm` },
  { id: 261, value: `Firestorm` },
  { id: 262, value: `Fixer` },
  { id: 263, value: `Flash` },
  { id: 264, value: `Flash Gordon` },
  { id: 265, value: `Flash II` },
  { id: 266, value: `Flash III` },
  { id: 267, value: `Flash IV` },
  { id: 268, value: `Forge` },
  { id: 269, value: `Franklin Richards` },
  { id: 270, value: `Franklin Storm` },
  { id: 271, value: `Frenzy` },
  { id: 272, value: `Frigga` },
  { id: 273, value: `Galactus` },
  { id: 274, value: `Gambit` },
  { id: 275, value: `Gamora` },
  { id: 276, value: `Garbage Man` },
  { id: 277, value: `Gary Bell` },
  { id: 278, value: `General Zod` },
  { id: 279, value: `Genesis` },
  { id: 280, value: `Ghost Rider` },
  { id: 281, value: `Ghost Rider II` },
  { id: 282, value: `Giant-Man` },
  { id: 283, value: `Giant-Man II` },
  { id: 284, value: `Giganta` },
  { id: 285, value: `Gladiator` },
  { id: 286, value: `Goblin Queen` },
  { id: 287, value: `Godzilla` },
  { id: 288, value: `Gog` },
  { id: 289, value: `Goku` },
  { id: 290, value: `Goliath` },
  { id: 291, value: `Goliath` },
  { id: 292, value: `Goliath` },
  { id: 293, value: `Goliath IV` },
  { id: 294, value: `Gorilla Grodd` },
  { id: 295, value: `Granny Goodness` },
  { id: 296, value: `Gravity` },
  { id: 297, value: `Greedo` },
  { id: 298, value: `Green Arrow` },
  { id: 299, value: `Green Goblin` },
  { id: 300, value: `Green Goblin II` },
  { id: 301, value: `Green Goblin III` },
  { id: 302, value: `Green Goblin IV` },
  { id: 303, value: `Groot` },
  { id: 304, value: `Guardian` },
  { id: 305, value: `Guy Gardner` },
  { id: 306, value: `Hal Jordan` },
  { id: 307, value: `Han Solo` },
  { id: 308, value: `Hancock` },
  { id: 309, value: `Harley Quinn` },
  { id: 310, value: `Harry Potter` },
  { id: 311, value: `Havok` },
  { id: 312, value: `Hawk` },
  { id: 313, value: `Hawkeye` },
  { id: 314, value: `Hawkeye II` },
  { id: 315, value: `Hawkgirl` },
  { id: 316, value: `Hawkman` },
  { id: 317, value: `Hawkwoman` },
  { id: 318, value: `Hawkwoman II` },
  { id: 319, value: `Hawkwoman III` },
  { id: 320, value: `Heat Wave` },
  { id: 321, value: `Hela` },
  { id: 322, value: `Hellboy` },
  { id: 323, value: `Hellcat` },
  { id: 324, value: `Hellstorm` },
  { id: 325, value: `Hercules` },
  { id: 326, value: `Hiro Nakamura` },
  { id: 327, value: `Hit-Girl` },
  { id: 328, value: `Hobgoblin` },
  { id: 329, value: `Hollow` },
  { id: 330, value: `Hope Summers` },
  { id: 331, value: `Howard the Duck` },
  { id: 332, value: `Hulk` },
  { id: 333, value: `Human Torch` },
  { id: 334, value: `Huntress` },
  { id: 335, value: `Husk` },
  { id: 336, value: `Hybrid` },
  { id: 337, value: `Hydro-Man` },
  { id: 338, value: `Hyperion` },
  { id: 339, value: `Iceman` },
  { id: 340, value: `Impulse` },
  { id: 341, value: `Indiana Jones` },
  { id: 342, value: `Indigo` },
  { id: 343, value: `Ink` },
  { id: 344, value: `Invisible Woman` },
  { id: 345, value: `Iron Fist` },
  { id: 346, value: `Iron Man` },
  { id: 347, value: `Iron Monger` },
  { id: 348, value: `Isis` },
  { id: 349, value: `Jack Bauer` },
  { id: 350, value: `Jack of Hearts` },
  { id: 351, value: `Jack-Jack` },
  { id: 352, value: `James Bond` },
  { id: 353, value: `James T. Kirk` },
  { id: 354, value: `Jar Jar Binks` },
  { id: 355, value: `Jason Bourne` },
  { id: 356, value: `Jean Grey` },
  { id: 357, value: `Jean-Luc Picard` },
  { id: 358, value: `Jennifer Kale` },
  { id: 359, value: `Jesse Quick` },
  { id: 360, value: `Jessica Cruz` },
  { id: 361, value: `Jessica Jones` },
  { id: 362, value: `Jessica Sanders` },
  { id: 363, value: `Jigsaw` },
  { id: 364, value: `Jim Powell` },
  { id: 365, value: `JJ Powell` },
  { id: 366, value: `Johann Krauss` },
  { id: 367, value: `John Constantine` },
  { id: 368, value: `John Stewart` },
  { id: 369, value: `John Wraith` },
  { id: 370, value: `Joker` },
  { id: 371, value: `Jolt` },
  { id: 372, value: `Jubilee` },
  { id: 373, value: `Judge Dredd` },
  { id: 374, value: `Juggernaut` },
  { id: 375, value: `Junkpile` },
  { id: 376, value: `Justice` },
  { id: 377, value: `Jyn Erso` },
  { id: 378, value: `K-2SO` },
  { id: 379, value: `Kang` },
  { id: 380, value: `Kathryn Janeway` },
  { id: 381, value: `Katniss Everdeen` },
  { id: 382, value: `Kevin 11` },
  { id: 383, value: `Kick-Ass` },
  { id: 384, value: `Kid Flash` },
  { id: 385, value: `Kid Flash II` },
  { id: 386, value: `Killer Croc` },
  { id: 387, value: `Killer Frost` },
  { id: 388, value: `Kilowog` },
  { id: 389, value: `King Kong` },
  { id: 390, value: `King Shark` },
  { id: 391, value: `Kingpin` },
  { id: 392, value: `Klaw` },
  { id: 393, value: `Kool-Aid Man` },
  { id: 394, value: `Kraven II` },
  { id: 395, value: `Kraven the Hunter` },
  { id: 396, value: `Krypto` },
  { id: 397, value: `Kyle Rayner` },
  { id: 398, value: `Kylo Ren` },
  { id: 399, value: `Lady Bullseye` },
  { id: 400, value: `Lady Deathstrike` },
  { id: 401, value: `Leader` },
  { id: 402, value: `Leech` },
  { id: 403, value: `Legion` },
  { id: 404, value: `Leonardo` },
  { id: 405, value: `Lex Luthor` },
  { id: 406, value: `Light Lass` },
  { id: 407, value: `Lightning Lad` },
  { id: 408, value: `Lightning Lord` },
  { id: 409, value: `Living Brain` },
  { id: 410, value: `Living Tribunal` },
  { id: 411, value: `Liz Sherman` },
  { id: 412, value: `Lizard` },
  { id: 413, value: `Lobo` },
  { id: 414, value: `Loki` },
  { id: 415, value: `Longshot` },
  { id: 416, value: `Luke Cage` },
  { id: 417, value: `Luke Campbell` },
  { id: 418, value: `Luke Skywalker` },
  { id: 419, value: `Luna` },
  { id: 420, value: `Lyja` },
  { id: 421, value: `Mach-IV` },
  { id: 422, value: `Machine Man` },
  { id: 423, value: `Magneto` },
  { id: 424, value: `Magog` },
  { id: 425, value: `Magus` },
  { id: 426, value: `Man of Miracles` },
  { id: 427, value: `Man-Bat` },
  { id: 428, value: `Man-Thing` },
  { id: 429, value: `Man-Wolf` },
  { id: 430, value: `Mandarin` },
  { id: 431, value: `Mantis` },
  { id: 432, value: `Martian Manhunter` },
  { id: 433, value: `Marvel Girl` },
  { id: 434, value: `Master Brood` },
  { id: 435, value: `Master Chief` },
  { id: 436, value: `Match` },
  { id: 437, value: `Matt Parkman` },
  { id: 438, value: `Maverick` },
  { id: 439, value: `Maxima` },
  { id: 440, value: `Maya Herrera` },
  { id: 441, value: `Medusa` },
  { id: 442, value: `Meltdown` },
  { id: 443, value: `Mephisto` },
  { id: 444, value: `Mera` },
  { id: 445, value: `Metallo` },
  { id: 446, value: `Metamorpho` },
  { id: 447, value: `Meteorite` },
  { id: 448, value: `Metron` },
  { id: 449, value: `Micah Sanders` },
  { id: 450, value: `Michelangelo` },
  { id: 451, value: `Micro Lad` },
  { id: 452, value: `Mimic` },
  { id: 453, value: `Minna Murray` },
  { id: 454, value: `Misfit` },
  { id: 455, value: `Miss Martian` },
  { id: 456, value: `Mister Fantastic` },
  { id: 457, value: `Mister Freeze` },
  { id: 458, value: `Mister Knife` },
  { id: 459, value: `Mister Mxyzptlk` },
  { id: 460, value: `Mister Sinister` },
  { id: 461, value: `Mister Zsasz` },
  { id: 462, value: `Mockingbird` },
  { id: 463, value: `MODOK` },
  { id: 464, value: `Mogo` },
  { id: 465, value: `Mohinder Suresh` },
  { id: 466, value: `Moloch` },
  { id: 467, value: `Molten Man` },
  { id: 468, value: `Monarch` },
  { id: 469, value: `Monica Dawson` },
  { id: 470, value: `Moon Knight` },
  { id: 471, value: `Moonstone` },
  { id: 472, value: `Morlun` },
  { id: 473, value: `Morph` },
  { id: 474, value: `Moses Magnum` },
  { id: 475, value: `Mr Immortal` },
  { id: 476, value: `Mr Incredible` },
  { id: 477, value: `Ms Marvel II` },
  { id: 478, value: `Multiple Man` },
  { id: 479, value: `Mysterio` },
  { id: 480, value: `Mystique` },
  { id: 481, value: `Namor` },
  { id: 482, value: `Namor` },
  { id: 483, value: `Namora` },
  { id: 484, value: `Namorita` },
  { id: 485, value: `Naruto Uzumaki` },
  { id: 486, value: `Nathan Petrelli` },
  { id: 487, value: `Nebula` },
  { id: 488, value: `Negasonic Teenage Warhead` },
  { id: 489, value: `Nick Fury` },
  { id: 490, value: `Nightcrawler` },
  { id: 491, value: `Nightwing` },
  { id: 492, value: `Niki Sanders` },
  { id: 493, value: `Nina Theroux` },
  { id: 494, value: `Nite Owl II` },
  { id: 495, value: `Northstar` },
  { id: 496, value: `Nova` },
  { id: 497, value: `Nova` },
  { id: 498, value: `Odin` },
  { id: 499, value: `Offspring` },
  { id: 500, value: `Omega Red` },
  { id: 501, value: `Omniscient` },
  { id: 502, value: `One Punch Man` },
  { id: 503, value: `One-Above-All` },
  { id: 504, value: `Onslaught` },
  { id: 505, value: `Oracle` },
  { id: 506, value: `Osiris` },
  { id: 507, value: `Overtkill` },
  { id: 508, value: `Ozymandias` },
  { id: 509, value: `Parademon` },
  { id: 510, value: `Paul Blart` },
  { id: 511, value: `Penance` },
  { id: 512, value: `Penance I` },
  { id: 513, value: `Penance II` },
  { id: 514, value: `Penguin` },
  { id: 515, value: `Phantom` },
  { id: 516, value: `Phantom Girl` },
  { id: 517, value: `Phoenix` },
  { id: 518, value: `Plantman` },
  { id: 519, value: `Plastic Lad` },
  { id: 520, value: `Plastic Man` },
  { id: 521, value: `Plastique` },
  { id: 522, value: `Poison Ivy` },
  { id: 523, value: `Polaris` },
  { id: 524, value: `Power Girl` },
  { id: 525, value: `Power Man` },
  { id: 526, value: `Predator` },
  { id: 527, value: `Professor X` },
  { id: 528, value: `Professor Zoom` },
  { id: 529, value: `Psylocke` },
  { id: 530, value: `Punisher` },
  { id: 531, value: `Purple Man` },
  { id: 532, value: `Pyro` },
  { id: 533, value: `Q` },
  { id: 534, value: `Quantum` },
  { id: 535, value: `Question` },
  { id: 536, value: `Quicksilver` },
  { id: 537, value: `Quill` },
  { id: 538, value: `Ra's Al Ghul` },
  { id: 539, value: `Rachel Pirzad` },
  { id: 540, value: `Rambo` },
  { id: 541, value: `Raphael` },
  { id: 542, value: `Raven` },
  { id: 543, value: `Ray` },
  { id: 544, value: `Razor-Fist II` },
  { id: 545, value: `Red Arrow` },
  { id: 546, value: `Red Hood` },
  { id: 547, value: `Red Hulk` },
  { id: 548, value: `Red Mist` },
  { id: 549, value: `Red Robin` },
  { id: 550, value: `Red Skull` },
  { id: 551, value: `Red Tornado` },
  { id: 552, value: `Redeemer II` },
  { id: 553, value: `Redeemer III` },
  { id: 554, value: `Renata Soliz` },
  { id: 555, value: `Rey` },
  { id: 556, value: `Rhino` },
  { id: 557, value: `Rick Flag` },
  { id: 558, value: `Riddler` },
  { id: 559, value: `Rip Hunter` },
  { id: 560, value: `Ripcord` },
  { id: 561, value: `Robin` },
  { id: 562, value: `Robin II` },
  { id: 563, value: `Robin III` },
  { id: 564, value: `Robin V` },
  { id: 565, value: `Robin VI` },
  { id: 566, value: `Rocket Raccoon` },
  { id: 567, value: `Rogue` },
  { id: 568, value: `Ronin` },
  { id: 569, value: `Rorschach` },
  { id: 570, value: `Sabretooth` },
  { id: 571, value: `Sage` },
  { id: 572, value: `Sandman` },
  { id: 573, value: `Sasquatch` },
  { id: 574, value: `Sauron` },
  { id: 575, value: `Savage Dragon` },
  { id: 576, value: `Scarecrow` },
  { id: 577, value: `Scarlet Spider` },
  { id: 578, value: `Scarlet Spider II` },
  { id: 579, value: `Scarlet Witch` },
  { id: 580, value: `Scorpia` },
  { id: 581, value: `Scorpion` },
  { id: 582, value: `Sebastian Shaw` },
  { id: 583, value: `Sentry` },
  { id: 584, value: `Shadow King` },
  { id: 585, value: `Shadow Lass` },
  { id: 586, value: `Shadowcat` },
  { id: 587, value: `Shang-Chi` },
  { id: 588, value: `Shatterstar` },
  { id: 589, value: `She-Hulk` },
  { id: 590, value: `She-Thing` },
  { id: 591, value: `Shocker` },
  { id: 592, value: `Shriek` },
  { id: 593, value: `Shrinking Violet` },
  { id: 594, value: `Sif` },
  { id: 595, value: `Silk` },
  { id: 596, value: `Silk Spectre` },
  { id: 597, value: `Silk Spectre II` },
  { id: 598, value: `Silver Surfer` },
  { id: 599, value: `Silverclaw` },
  { id: 600, value: `Simon Baz` },
  { id: 601, value: `Sinestro` },
  { id: 602, value: `Siren` },
  { id: 603, value: `Siren II` },
  { id: 604, value: `Siryn` },
  { id: 605, value: `Skaar` },
  { id: 606, value: `Snake-Eyes` },
  { id: 607, value: `Snowbird` },
  { id: 608, value: `Sobek` },
  { id: 609, value: `Solomon Grundy` },
  { id: 610, value: `Songbird` },
  { id: 611, value: `Space Ghost` },
  { id: 612, value: `Spawn` },
  { id: 613, value: `Spectre` },
  { id: 614, value: `Speedball` },
  { id: 615, value: `Speedy` },
  { id: 616, value: `Speedy` },
  { id: 617, value: `Spider-Carnage` },
  { id: 618, value: `Spider-Girl` },
  { id: 619, value: `Spider-Gwen` },
  { id: 620, value: `Spider-Man` },
  { id: 621, value: `Spider-Man` },
  { id: 622, value: `Spider-Man` },
  { id: 623, value: `Spider-Woman` },
  { id: 624, value: `Spider-Woman II` },
  { id: 625, value: `Spider-Woman III` },
  { id: 626, value: `Spider-Woman IV` },
  { id: 627, value: `Spock` },
  { id: 628, value: `Spyke` },
  { id: 629, value: `Stacy X` },
  { id: 630, value: `Star-Lord` },
  { id: 631, value: `Stardust` },
  { id: 632, value: `Starfire` },
  { id: 633, value: `Stargirl` },
  { id: 634, value: `Static` },
  { id: 635, value: `Steel` },
  { id: 636, value: `Stephanie Powell` },
  { id: 637, value: `Steppenwolf` },
  { id: 638, value: `Storm` },
  { id: 639, value: `Stormtrooper` },
  { id: 640, value: `Sunspot` },
  { id: 641, value: `Superboy` },
  { id: 642, value: `Superboy-Prime` },
  { id: 643, value: `Supergirl` },
  { id: 644, value: `Superman` },
  { id: 645, value: `Swamp Thing` },
  { id: 646, value: `Swarm` },
  { id: 647, value: `Sylar` },
  { id: 648, value: `Synch` },
  { id: 649, value: `T-1000` },
  { id: 650, value: `T-800` },
  { id: 651, value: `T-850` },
  { id: 652, value: `T-X` },
  { id: 653, value: `Taskmaster` },
  { id: 654, value: `Tempest` },
  { id: 655, value: `Thanos` },
  { id: 656, value: `The Cape` },
  { id: 657, value: `The Comedian` },
  { id: 658, value: `Thing` },
  { id: 659, value: `Thor` },
  { id: 660, value: `Thor Girl` },
  { id: 661, value: `Thunderbird` },
  { id: 662, value: `Thunderbird II` },
  { id: 663, value: `Thunderbird III` },
  { id: 664, value: `Thunderstrike` },
  { id: 665, value: `Thundra` },
  { id: 666, value: `Tiger Shark` },
  { id: 667, value: `Tigra` },
  { id: 668, value: `Tinkerer` },
  { id: 669, value: `Titan` },
  { id: 670, value: `Toad` },
  { id: 671, value: `Toxin` },
  { id: 672, value: `Toxin` },
  { id: 673, value: `Tracy Strauss` },
  { id: 674, value: `Trickster` },
  { id: 675, value: `Trigon` },
  { id: 676, value: `Triplicate Girl` },
  { id: 677, value: `Triton` },
  { id: 678, value: `Two-Face` },
  { id: 679, value: `Ultragirl` },
  { id: 680, value: `Ultron` },
  { id: 681, value: `Utgard-Loki` },
  { id: 682, value: `Vagabond` },
  { id: 683, value: `Valerie Hart` },
  { id: 684, value: `Valkyrie` },
  { id: 685, value: `Vanisher` },
  { id: 686, value: `Vegeta` },
  { id: 687, value: `Venom` },
  { id: 688, value: `Venom II` },
  { id: 689, value: `Venom III` },
  { id: 690, value: `Venompool` },
  { id: 691, value: `Vertigo II` },
  { id: 692, value: `Vibe` },
  { id: 693, value: `Vindicator` },
  { id: 694, value: `Vindicator` },
  { id: 695, value: `Violator` },
  { id: 696, value: `Violet Parr` },
  { id: 697, value: `Vision` },
  { id: 698, value: `Vision II` },
  { id: 699, value: `Vixen` },
  { id: 700, value: `Vulcan` },
  { id: 701, value: `Vulture` },
  { id: 702, value: `Walrus` },
  { id: 703, value: `War Machine` },
  { id: 704, value: `Warbird` },
  { id: 705, value: `Warlock` },
  { id: 706, value: `Warp` },
  { id: 707, value: `Warpath` },
  { id: 708, value: `Wasp` },
  { id: 709, value: `Watcher` },
  { id: 710, value: `Weapon XI` },
  { id: 711, value: `White Canary` },
  { id: 712, value: `White Queen` },
  { id: 713, value: `Wildfire` },
  { id: 714, value: `Winter Soldier` },
  { id: 715, value: `Wiz Kid` },
  { id: 716, value: `Wolfsbane` },
  { id: 717, value: `Wolverine` },
  { id: 718, value: `Wonder Girl` },
  { id: 719, value: `Wonder Man` },
  { id: 720, value: `Wonder Woman` },
  { id: 721, value: `Wondra` },
  { id: 722, value: `Wyatt Wingfoot` },
  { id: 723, value: `X-23` },
  { id: 724, value: `X-Man` },
  { id: 725, value: `Yellow Claw` },
  { id: 726, value: `Yellowjacket` },
  { id: 727, value: `Yellowjacket II` },
  { id: 728, value: `Ymir` },
  { id: 729, value: `Yoda` },
  { id: 730, value: `Zatanna` },
  { id: 731, value: `Zoom` },
];

export default heroOptions;
